# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FTX.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(2000, 1500))
        MainWindow.setMaximumSize(QtCore.QSize(3000, 1500))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(2000, 1500))
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgba(238, 238, 238, 255);\n"
" border: 1px solid #393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1921, 81))
        self.frame_6.setStyleSheet("#frame_6{\n"
"background-color:#393E46;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(1680, 0, 241, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed {padding-top:5px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Minimize 3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed {padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(1590, 900, 661, 461))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color:#393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 1, 661, 1021))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setStyleSheet("#line_2{\n"
"background-color: #455364;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("#label_5{\n"
"color: rgb(255, 255, 0);}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setStyleSheet("#line_4{\n"
"background-color: #455364;\n"
"}")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_6.setStyleSheet("#line_6{\n"
"background-color:#455364;\n"
"}")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_4.addWidget(self.line_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_7.setStyleSheet("#line{\n"
"background-color: #455364;\n"
"}")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pinzhong = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinzhong.sizePolicy().hasHeightForWidth())
        self.pinzhong.setSizePolicy(sizePolicy)
        self.pinzhong.setMinimumSize(QtCore.QSize(0, 937))
        self.pinzhong.setStyleSheet("#pinzhong{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.pinzhong.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pinzhong.setObjectName("pinzhong")
        self.horizontalLayout_5.addWidget(self.pinzhong)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setStyleSheet("#line{\n"
"background-color: #455364;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.cangwei_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.cangwei_2.setStyleSheet("#cangwei_2{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.cangwei_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.cangwei_2.setObjectName("cangwei_2")
        self.horizontalLayout_5.addWidget(self.cangwei_2)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setStyleSheet("#line_3{\n"
"background-color: #455364;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.chengbenjia = QtWidgets.QLabel(self.layoutWidget1)
        self.chengbenjia.setStyleSheet("#chengbenjia{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.chengbenjia.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.chengbenjia.setObjectName("chengbenjia")
        self.horizontalLayout_5.addWidget(self.chengbenjia)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_5.setStyleSheet("#line_5{\n"
"background-color: #455364;\n"
"}")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.xianjia_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.xianjia_2.setStyleSheet("#xianjia_2{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.xianjia_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.xianjia_2.setObjectName("xianjia_2")
        self.horizontalLayout_5.addWidget(self.xianjia_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(1660, -210, 661, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setStyleSheet("QTabWidget#tabWidget::pane {\n"
"  \n"
"    background-color:#393E46;\n"
"  border: 1px solid; \n"
"    border-color: rgb(0, 65, 95);\n"
"  padding:1px;\n"
"  border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"} \n"
"\n"
"QTabBar::tab { \n"
"background-color:#393E46;\n"
"  border: 1px solid; \n"
"  padding:20px;\n"
"border-top-left-radius: 7px;\n"
"  border-top-right-radius: 7px;\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"} \n"
"QTabBar::tab:hover { \n"
"  border: 1px solid; \n"
"    background-color: rgb(157, 157, 157);\n"
"  padding:20px;\n"
"border-top-left-radius: 7px;\n"
"  border-top-right-radius: 7px;\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"} \n"
"QTabBar::tab:selected { \n"
"  border: 1px solid; \n"
"    background-color: rgb(157, 157, 157);\n"
"  padding:20px;\n"
"border-top-left-radius: 7px;\n"
"  border-top-right-radius: 7px;\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(12, 12))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 10, 481, 171))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xiadan_zhiying = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_zhiying.sizePolicy().hasHeightForWidth())
        self.xiadan_zhiying.setSizePolicy(sizePolicy)
        self.xiadan_zhiying.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.xiadan_zhiying.setStyleSheet("QLineEdit#xiadan_zhiying{ border-radius: 10px; }")
        self.xiadan_zhiying.setObjectName("xiadan_zhiying")
        self.verticalLayout.addWidget(self.xiadan_zhiying)
        self.xiadan_ruchang = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_ruchang.sizePolicy().hasHeightForWidth())
        self.xiadan_ruchang.setSizePolicy(sizePolicy)
        self.xiadan_ruchang.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.xiadan_ruchang.setStyleSheet("QLineEdit#xiadan_ruchang { border-radius: 10px; }")
        self.xiadan_ruchang.setObjectName("xiadan_ruchang")
        self.verticalLayout.addWidget(self.xiadan_ruchang)
        self.xiadan_zhisun_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_zhisun_2.sizePolicy().hasHeightForWidth())
        self.xiadan_zhisun_2.setSizePolicy(sizePolicy)
        self.xiadan_zhisun_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.xiadan_zhisun_2.setStyleSheet("QLineEdit#xiadan_zhisun_2 { border-radius: 10px; }")
        self.xiadan_zhisun_2.setObjectName("xiadan_zhisun_2")
        self.verticalLayout.addWidget(self.xiadan_zhisun_2)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 10, 141, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zhiying = QtWidgets.QLabel(self.layoutWidget3)
        self.zhiying.setAlignment(QtCore.Qt.AlignCenter)
        self.zhiying.setObjectName("zhiying")
        self.verticalLayout_2.addWidget(self.zhiying)
        self.ruchang = QtWidgets.QLabel(self.layoutWidget3)
        self.ruchang.setAlignment(QtCore.Qt.AlignCenter)
        self.ruchang.setObjectName("ruchang")
        self.verticalLayout_2.addWidget(self.ruchang)
        self.zhisun = QtWidgets.QLabel(self.layoutWidget3)
        self.zhisun.setAlignment(QtCore.Qt.AlignCenter)
        self.zhisun.setObjectName("zhisun")
        self.verticalLayout_2.addWidget(self.zhisun)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(110, 180, 511, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xiadan_jiancang = QtWidgets.QCheckBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_jiancang.sizePolicy().hasHeightForWidth())
        self.xiadan_jiancang.setSizePolicy(sizePolicy)
        self.xiadan_jiancang.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.xiadan_jiancang.setStyleSheet("#xiadan_jiancang{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.xiadan_jiancang.setText("市价")
        self.xiadan_jiancang.setCheckable(True)
        self.xiadan_jiancang.setChecked(False)
        self.xiadan_jiancang.setAutoRepeat(False)
        self.xiadan_jiancang.setAutoExclusive(False)
        self.xiadan_jiancang.setTristate(False)
        self.xiadan_jiancang.setObjectName("xiadan_jiancang")
        self.horizontalLayout_3.addWidget(self.xiadan_jiancang)
        self.xiadan_maker = QtWidgets.QCheckBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_maker.sizePolicy().hasHeightForWidth())
        self.xiadan_maker.setSizePolicy(sizePolicy)
        self.xiadan_maker.setStyleSheet("#xiadan_maker{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.xiadan_maker.setChecked(True)
        self.xiadan_maker.setObjectName("xiadan_maker")
        self.horizontalLayout_3.addWidget(self.xiadan_maker)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(110, 280, 511, 101))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xiadan_zuoduo = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_zuoduo.sizePolicy().hasHeightForWidth())
        self.xiadan_zuoduo.setSizePolicy(sizePolicy)
        self.xiadan_zuoduo.setStyleSheet("QPushButton#xiadan_zuoduo {\n"
"background-color:#53d66d;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"\n"
"QPushButton#xiadan_zuoduo:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #85ff9e, stop: 1 #85ff9e\n"
"        );\n"
"    }\n"
"\n"
"QPushButton#xiadan_zuoduo:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #55ff63, stop: 1 #55ff63\n"
"        );\n"
"    }")
        self.xiadan_zuoduo.setObjectName("xiadan_zuoduo")
        self.horizontalLayout_6.addWidget(self.xiadan_zuoduo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem)
        self.xiadan_zuokong = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiadan_zuokong.sizePolicy().hasHeightForWidth())
        self.xiadan_zuokong.setSizePolicy(sizePolicy)
        self.xiadan_zuokong.setStyleSheet("QPushButton#xiadan_zuokong {\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ff4141, stop: 1 #ff4141\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#xiadan_zuokong:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ff6363, stop: 1 #ff6363\n"
"        );\n"
"    }\n"
"\n"
"QPushButton#xiadan_zuokong:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #ff2a2a, stop: 1 #ff2a2a\n"
"        );\n"
"    }")
        self.xiadan_zuokong.setObjectName("xiadan_zuokong")
        self.horizontalLayout_6.addWidget(self.xiadan_zuokong)
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(20, 190, 71, 51))
        self.label_29.setStyleSheet("#label_29{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 240, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setStyleSheet("")
        self.doubleSpinBox.setReadOnly(False)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setMaximum(2.0)
        self.doubleSpinBox.setSingleStep(0.25)
        self.doubleSpinBox.setProperty("value", 2.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 10, 481, 171))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chufajia = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chufajia.sizePolicy().hasHeightForWidth())
        self.chufajia.setSizePolicy(sizePolicy)
        self.chufajia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.chufajia.setStyleSheet("QLineEdit { border-radius: 10px; }")
        self.chufajia.setObjectName("chufajia")
        self.verticalLayout_3.addWidget(self.chufajia)
        self.xianjia = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xianjia.sizePolicy().hasHeightForWidth())
        self.xianjia.setSizePolicy(sizePolicy)
        self.xianjia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.xianjia.setStyleSheet("QLineEdit { border-radius: 10px; }")
        self.xianjia.setObjectName("xianjia")
        self.verticalLayout_3.addWidget(self.xianjia)
        self.cangwei = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cangwei.sizePolicy().hasHeightForWidth())
        self.cangwei.setSizePolicy(sizePolicy)
        self.cangwei.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cangwei.setStyleSheet("QLineEdit { border-radius: 10px; }")
        self.cangwei.setObjectName("cangwei")
        self.verticalLayout_3.addWidget(self.cangwei)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 10, 141, 171))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(110, 280, 511, 101))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton#pushButton_9 {\n"
"background-color:#53d66d;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"\n"
"QPushButton#pushButton_9:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #85ff9e, stop: 1 #85ff9e\n"
"        );\n"
"    }\n"
"\n"
"QPushButton#pushButton_9:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #55ff63, stop: 1 #55ff63\n"
"        );\n"
"    }")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_9.addWidget(self.pushButton_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton#pushButton_10 {\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ff4141, stop: 1 #ff4141\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#pushButton_10:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ff6363, stop: 1 #ff6363\n"
"        );\n"
"    }\n"
"\n"
"QPushButton#pushButton_10:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #ff2a2a, stop: 1 #ff2a2a\n"
"        );\n"
"    }")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(0, 200, 101, 41))
        self.comboBox.setStyleSheet("QComboBox#comboBox::drop-down {border:none\n"
"}\n"
"QComboBox#comboBox{\n"
"background-color: rgb(89, 97, 109);\n"
"border-radius:20px;\n"
"color: white;\n"
"}")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_4)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 200, 511, 41))
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.horizontalSlider.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.horizontalSlider.setProperty("value", 99)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(25)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(40, 250, 61, 41))
        self.label_14.setStyleSheet("#checkBox_4{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 310, 161, 71))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3 {\n"
"background-color: #8888cc;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"\n"
"QPushButton#pushButton_3:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #aaaaff, stop: 1 #aaaaff\n"
"        );\n"
"    }\n"
"\n"
"QPushButton#pushButton_3:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #6b6ba0, stop: 1 #6b6ba0\n"
"        );\n"
"    }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(150, 50, 451, 221))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.id = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.id.sizePolicy().hasHeightForWidth())
        self.id.setSizePolicy(sizePolicy)
        self.id.setStyleSheet("QLineEdit { border-radius: 10px; }")
        self.id.setObjectName("id")
        self.verticalLayout_5.addWidget(self.id)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("QLineEdit { border-radius: 10px; }")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 50, 141, 221))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(-440, 170, 721, 291))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: #393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 10, 701, 271))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.yingli = QtWidgets.QLabel(self.layoutWidget8)
        self.yingli.setStyleSheet("#yingli{font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.yingli.setObjectName("yingli")
        self.gridLayout.addWidget(self.yingli, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_13.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.zhanghuzijin = QtWidgets.QLabel(self.layoutWidget8)
        self.zhanghuzijin.setStyleSheet("#zhanghuzijin{font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.zhanghuzijin.setObjectName("zhanghuzijin")
        self.gridLayout.addWidget(self.zhanghuzijin, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setLineWidth(0)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-50, 930, 721, 531))
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color: #393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(40, 140, 641, 361))
        self.frame_2.setStyleSheet("#frame_2{    border: 1px solid; \n"
"border-color:#EEEEEE;\n"
"    background-color: #393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(0, 0, 641, 529))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("#label_11{\n"
"color: rgb(255, 255, 0);}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_15.setStyleSheet("#line_15{\n"
"background-color: #455364;\n"
"}")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_14.addWidget(self.line_15)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("#label_15{\n"
"color: rgb(255, 255, 0);}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_10.setStyleSheet("#line_10{\n"
"background-color: #455364;\n"
"}")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_14.addWidget(self.line_10)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("#label_12{\n"
"color: rgb(255, 255, 0);}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_11.setStyleSheet("#line_11{\n"
"background-color: #455364;\n"
"}")
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_14.addWidget(self.line_11)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setStyleSheet("#label_28{\n"
"color: rgb(255, 255, 0);}")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_14.setStyleSheet("#line_14{\n"
"background-color: #455364;\n"
"}")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_14.addWidget(self.line_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_12.setStyleSheet("")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_10.addWidget(self.line_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_16.setStyleSheet("#label_16{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_16.setStyleSheet("#line_16{\n"
"background-color: #455364;\n"
"}")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.horizontalLayout_15.addWidget(self.line_16)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_25.setStyleSheet("#label_25{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_8.setStyleSheet("#line_8{\n"
"background-color: #455364;\n"
"}")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_15.addWidget(self.line_8)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_26.setStyleSheet("#label_26{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_9.setStyleSheet("#line_9{\n"
"background-color: #455364;\n"
"}")
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_15.addWidget(self.line_9)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 460))
        self.label_27.setStyleSheet("#label_27{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.label_27.setText("")
        self.label_27.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_13.setStyleSheet("#line_13{\n"
"background-color: #455364;\n"
"}")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_15.addWidget(self.line_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.layoutWidget10 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(40, 40, 641, 71))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chongbi = QtWidgets.QPushButton(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chongbi.sizePolicy().hasHeightForWidth())
        self.chongbi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.chongbi.setFont(font)
        self.chongbi.setStyleSheet("QPushButton#chongbi {;\n"
"    color: #333;\n"
"    border: 2px solid #2B4865;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #E1FFEE, stop: 1 #00ADB5\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#chongbi:hover {        background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0  #00ADB5, stop: 1 #e7fff3\n"
"        );\n"
"\n"
"    }\n"
"\n"
"QPushButton#chongbi:pressed {\n"
"    border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(147, 246, 250, 255), stop:0.100121 rgba(130, 240, 245, 255), stop:0.2 rgba(118, 235, 240, 255), stop:0.3 rgba(101, 229, 235, 255), stop:0.4 rgba(86, 224, 230, 255), stop:0.5 rgba(70, 219, 225, 255), stop:0.6 rgba(56, 213, 220, 255), stop:0.7 rgba(42, 208, 215, 255), stop:0.8 rgba(28, 202, 210, 255), stop:0.9 rgba(12, 197, 205, 255), stop:1 rgba(0, 192, 200, 255));\n"
"    }\n"
"")
        self.chongbi.setObjectName("chongbi")
        self.horizontalLayout_7.addWidget(self.chongbi)
        self.tibi = QtWidgets.QPushButton(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tibi.sizePolicy().hasHeightForWidth())
        self.tibi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tibi.setFont(font)
        self.tibi.setStyleSheet("QPushButton#tibi {;\n"
"    color: #333;\n"
"    border: 2px solid #2B4865;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #E1FFEE, stop: 1 #00ADB5\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#tibi:hover {        background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0  #00ADB5, stop: 1 #e7fff3\n"
"        );\n"
"\n"
"    }\n"
"\n"
"QPushButton#tibi:pressed {\n"
"    border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(147, 246, 250, 255), stop:0.100121 rgba(130, 240, 245, 255), stop:0.2 rgba(118, 235, 240, 255), stop:0.3 rgba(101, 229, 235, 255), stop:0.4 rgba(86, 224, 230, 255), stop:0.5 rgba(70, 219, 225, 255), stop:0.6 rgba(56, 213, 220, 255), stop:0.7 rgba(42, 208, 215, 255), stop:0.8 rgba(28, 202, 210, 255), stop:0.9 rgba(12, 197, 205, 255), stop:1 rgba(0, 192, 200, 255));\n"
"    }\n"
"")
        self.tibi.setObjectName("tibi")
        self.horizontalLayout_7.addWidget(self.tibi)
        self.lishidingdan = QtWidgets.QPushButton(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lishidingdan.sizePolicy().hasHeightForWidth())
        self.lishidingdan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lishidingdan.setFont(font)
        self.lishidingdan.setStyleSheet("QPushButton#lishidingdan {;\n"
"    color: #333;\n"
"    border: 2px solid #2B4865;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #E1FFEE, stop: 1 #00ADB5\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#lishidingdan:hover {        background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0  #00ADB5, stop: 1 #e7fff3\n"
"        );\n"
"\n"
"    }\n"
"\n"
"QPushButton#lishidingdan:pressed {\n"
"    border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(147, 246, 250, 255), stop:0.100121 rgba(130, 240, 245, 255), stop:0.2 rgba(118, 235, 240, 255), stop:0.3 rgba(101, 229, 235, 255), stop:0.4 rgba(86, 224, 230, 255), stop:0.5 rgba(70, 219, 225, 255), stop:0.6 rgba(56, 213, 220, 255), stop:0.7 rgba(42, 208, 215, 255), stop:0.8 rgba(28, 202, 210, 255), stop:0.9 rgba(12, 197, 205, 255), stop:1 rgba(0, 192, 200, 255));\n"
"    }\n"
"")
        self.lishidingdan.setObjectName("lishidingdan")
        self.horizontalLayout_7.addWidget(self.lishidingdan)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(780, 930, 481, 461))
        self.frame_7.setStyleSheet("#frame_7{\n"
"background-color: #393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget11 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 40, 421, 391))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.layoutWidget11)
        self.frame_13.setStyleSheet("#frame_13{\n"
"    background-color: rgba(238, 238, 238, 250);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.layoutWidget12 = QtWidgets.QWidget(self.frame_13)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 6, 401, 71))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{\n"
"border:none;\n"
"}\n"
"QPushButton#pushButton_4:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton#pushButton_4:pressed {padding-top:5px;\n"
"}\n"
"")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_18.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
"border:none;\n"
"}\n"
"QPushButton#pushButton_5:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton#pushButton_5:pressed {padding-top:5px;\n"
"}")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_18.addWidget(self.pushButton_5)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setStyleSheet("QPushButton#pushButton_14{\n"
"border:none;\n"
"}\n"
"QPushButton#pushButton_14:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton#pushButton_14:pressed {padding-top:5px;\n"
"}\n"
"")
        self.pushButton_14.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/列表清单.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon4)
        self.pushButton_14.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_18.addWidget(self.pushButton_14)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6{\n"
"border:none;\n"
"}\n"
"QPushButton#pushButton_6:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton#pushButton_6:pressed {padding-top:5px;\n"
"}")
        self.pushButton_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_18.addWidget(self.pushButton_6)
        self.verticalLayout_8.addWidget(self.frame_13)
        spacerItem4 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem4)
        self.frame_14 = QtWidgets.QFrame(self.layoutWidget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setStyleSheet("#frame_14{\n"
"    background-color: rgba(238, 238, 238, 250);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setLineWidth(26)
        self.frame_14.setMidLineWidth(16)
        self.frame_14.setObjectName("frame_14")
        self.layoutWidget13 = QtWidgets.QWidget(self.frame_14)
        self.layoutWidget13.setGeometry(QtCore.QRect(30, 10, 361, 61))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget13)
        self.comboBox_2.setStyleSheet("background-color: rgba(238, 238, 238, 250);\n"
"border:none")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet("QPushButton#pushButton_17 {;\n"
"    color: #333;\n"
"    border: 2px solid #2B4865;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: #EB1D36;\n"
"        \n"
"    padding: 5px;\n"
"    }\n"
"\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_8.addWidget(self.pushButton_17)
        self.verticalLayout_8.addWidget(self.frame_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem6)
        self.frame_12 = QtWidgets.QFrame(self.layoutWidget11)
        self.frame_12.setStyleSheet("#frame_12{\n"
"    background-color: rgba(238, 238, 238, 250);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_18.setGeometry(QtCore.QRect(320, 0, 91, 81))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:pressed {padding-top:5px;\n"
"}\n"
"")
        self.pushButton_18.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/去顶部.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon6)
        self.pushButton_18.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lishidingdan_2 = QtWidgets.QPushButton(self.frame_12)
        self.lishidingdan_2.setGeometry(QtCore.QRect(10, 20, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lishidingdan_2.sizePolicy().hasHeightForWidth())
        self.lishidingdan_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lishidingdan_2.setFont(font)
        self.lishidingdan_2.setStyleSheet("QPushButton#lishidingdan_2 {;\n"
"    color: #333;\n"
"    border: 2px solid #2B4865;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #E1FFEE, stop: 1 #00ADB5\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton#lishidingdan_2:hover {        background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0  #00ADB5, stop: 1 #e7fff3\n"
"        );\n"
"\n"
"    }\n"
"\n"
"QPushButton#lishidingdan_2:pressed {\n"
"    border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(147, 246, 250, 255), stop:0.100121 rgba(130, 240, 245, 255), stop:0.2 rgba(118, 235, 240, 255), stop:0.3 rgba(101, 229, 235, 255), stop:0.4 rgba(86, 224, 230, 255), stop:0.5 rgba(70, 219, 225, 255), stop:0.6 rgba(56, 213, 220, 255), stop:0.7 rgba(42, 208, 215, 255), stop:0.8 rgba(28, 202, 210, 255), stop:0.9 rgba(12, 197, 205, 255), stop:1 rgba(0, 192, 200, 255));\n"
"    }\n"
"")
        self.lishidingdan_2.setObjectName("lishidingdan_2")
        self.verticalLayout_8.addWidget(self.frame_12)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(-440, 20, 721, 111))
        self.frame_8.setStyleSheet("#frame_8{\n"
"    background-color:#393E46;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget14 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget14.setGeometry(QtCore.QRect(20, 10, 681, 91))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777196, 16777215))
        self.label_3.setStyleSheet("image: url(:/icon/clock_flat.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("#label_9{font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(318, 16777215))
        self.label_10.setStyleSheet("#label_10{font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(1790, 30, 401, 81))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.layoutWidget15 = QtWidgets.QWidget(self.frame_11)
        self.layoutWidget15.setGeometry(QtCore.QRect(10, 10, 361, 76))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(self.layoutWidget15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_16.setStyleSheet("QPushButton#pushButton_16 {\n"
"    border: none;\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"    }")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_12.addWidget(self.pushButton_16)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(760, -220, 461, 401))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_9 = QtWidgets.QFrame(self.frame_15)
        self.frame_9.setGeometry(QtCore.QRect(70, 30, 341, 341))
        self.frame_9.setStyleSheet("QFrame#frame_9{\n"
"border-radius: 170px;\n"
"    background-color: #393E46;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setGeometry(QtCore.QRect(0, 50, 341, 231))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.layoutWidget16 = QtWidgets.QWidget(self.frame_16)
        self.layoutWidget16.setGeometry(QtCore.QRect(80, 150, 261, 81))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.jinrixiadan = QtWidgets.QLabel(self.layoutWidget16)
        self.jinrixiadan.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.jinrixiadan.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.jinrixiadan.setTextFormat(QtCore.Qt.AutoText)
        self.jinrixiadan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.jinrixiadan.setIndent(0)
        self.jinrixiadan.setObjectName("jinrixiadan")
        self.horizontalLayout_11.addWidget(self.jinrixiadan)
        self.layoutWidget17 = QtWidgets.QWidget(self.frame_16)
        self.layoutWidget17.setGeometry(QtCore.QRect(0, 0, 341, 151))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget17)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: #FFFFFF")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.riyingkuipercent = QtWidgets.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.riyingkuipercent.setFont(font)
        self.riyingkuipercent.setStyleSheet("font: 24pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.riyingkuipercent.setTextFormat(QtCore.Qt.AutoText)
        self.riyingkuipercent.setScaledContents(False)
        self.riyingkuipercent.setAlignment(QtCore.Qt.AlignCenter)
        self.riyingkuipercent.setWordWrap(True)
        self.riyingkuipercent.setIndent(0)
        self.riyingkuipercent.setObjectName("riyingkuipercent")
        self.verticalLayout_9.addWidget(self.riyingkuipercent)
        self.sousuo = QtWidgets.QLineEdit(self.frame)
        self.sousuo.setGeometry(QtCore.QRect(760, 80, 461, 71))
        self.sousuo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sousuo.setStyleSheet("QLineEdit#sousuo { \n"
"    border-radius:20px\n"
" }")
        self.sousuo.setInputMask("")
        self.sousuo.setText("")
        self.sousuo.setCursorPosition(0)
        self.sousuo.setAlignment(QtCore.Qt.AlignCenter)
        self.sousuo.setDragEnabled(False)
        self.sousuo.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.sousuo.setObjectName("sousuo")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(760, 80, 71, 71))
        self.label_2.setStyleSheet("image: url(:/icon/search.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(1160, 90, 51, 51))
        self.pushButton_11.setStyleSheet("QPushButton#pushButton_11 {border:none}\n"
"QPushButton#pushButton_11:hover{\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton#pushButton_11:pressed {padding-top:5px;\n"
"}")
        self.pushButton_11.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.sousuo.raise_()
        self.frame_15.raise_()
        self.tabWidget.raise_()
        self.frame_6.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frame_3.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.frame_11.raise_()
        self.label_2.raise_()
        self.pushButton_11.raise_()
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.xiadan_jiancang.clicked.connect(self.xiadan_maker.toggle) # type: ignore
        self.xiadan_maker.clicked.connect(self.xiadan_jiancang.toggle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">品种</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">仓位</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">成本价</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">限价</span></p></body></html>"))
        self.pinzhong.setText(_translate("MainWindow", "N/A"))
        self.cangwei_2.setText(_translate("MainWindow", "N/A"))
        self.chengbenjia.setText(_translate("MainWindow", "N/A"))
        self.xianjia_2.setText(_translate("MainWindow", "N/A"))
        self.zhiying.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">止损：</span></p></body></html>"))
        self.ruchang.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">入场：</span></p></body></html>"))
        self.zhisun.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">止盈：</span></p></body></html>"))
        self.xiadan_maker.setText(_translate("MainWindow", "只做Maker"))
        self.xiadan_zuoduo.setText(_translate("MainWindow", "做多"))
        self.xiadan_zuokong.setText(_translate("MainWindow", "做空"))
        self.label_29.setText(_translate("MainWindow", "风控："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "下单"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">触发价：</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">限价：</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#e3e3e3;\">仓位：</span></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "做多(做空止损）"))
        self.pushButton_10.setText(_translate("MainWindow", "做空（做多止损）"))
        self.comboBox.setItemText(0, _translate("MainWindow", "限价"))
        self.comboBox.setItemText(1, _translate("MainWindow", "市价"))
        self.comboBox.setItemText(2, _translate("MainWindow", "市价止损"))
        self.comboBox.setItemText(3, _translate("MainWindow", "限价止损"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "下单2"))
        self.pushButton_3.setText(_translate("MainWindow", "设置"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e3e3e3;\">ID:</span></p></body></html>"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "价格"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "仓位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "警报"))
        self.yingli.setText(_translate("MainWindow", "0.0"))
        self.label_13.setText(_translate("MainWindow", "账户资金($):"))
        self.zhanghuzijin.setText(_translate("MainWindow", "0.0"))
        self.label_8.setText(_translate("MainWindow", "总盈利(%)："))
        self.label_11.setText(_translate("MainWindow", "ID"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">品种</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#e3e3e3;\">仓位</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>方向</p></body></html>"))
        self.chongbi.setText(_translate("MainWindow", "充币"))
        self.tibi.setText(_translate("MainWindow", "提币"))
        self.lishidingdan.setText(_translate("MainWindow", "历史订单记录"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.pushButton_17.setText(_translate("MainWindow", "市价全平"))
        self.lishidingdan_2.setText(_translate("MainWindow", "取消所有挂单"))
        self.label_9.setText(_translate("MainWindow", "当前时间："))
        self.label_10.setText(_translate("MainWindow", "N/A"))
        self.label.setText(_translate("MainWindow", "N/A"))
        self.pushButton_16.setText(_translate("MainWindow", "0.0"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#ffffff;\">今日开单数：</span></p></body></html>"))
        self.jinrixiadan.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">日盈亏</span></p></body></html>"))
        self.riyingkuipercent.setText(_translate("MainWindow", "0.00%"))
